apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybridapp
spec:
  selector:
    matchLabels:
      app: hybridapp
  template:
    metadata:
      labels:
        app: hybridapp
    spec:
      containers:
      - image: okteto.dev/hybrid-test-hybridapp:okteto
        name: hybridapp

---

apiVersion: v1
kind: Service
metadata:
  name: hybridapp
spec:
  type: ClusterIP
  ports:
  - name: "app"
    port: 80
  selector:
    app: hybridapp

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hybridapp
  annotations:
    dev.okteto.com/generate-host: hybridapp
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: hybridapp
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific